---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# r4aPrimer

<!-- badges: start -->
![Render & Deploy
Site](https://github.com/jhelvy//workflows/Render%20&%20Deploy%20Site/badge.svg)
[![License:
MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT)
<!-- badges: end -->

**Description**:

```{r child = '_description.Rmd'}
```

For more details, please see the [course website](https://jhelvy.github.io/r4aPrimer/).

**Learning Objectives**:

```{r child = '_learning-objectives.Rmd'}
```

**Prerequisites**:

```{r child = '_prerequisites.Rmd'}
```

### Acknowledgments

This course was inspired by many other courses / resources that cover
similar material - see the course [about
page](http://jhelvy.github.io/r4aPrimer/about.html) for more details.
